# Generated by Django 6.0.4 on 2026-04-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('mesas', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_enviadas', to='usuarios.usuario')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedido')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_recibidas', to='usuarios.usuario')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesas.sesionmesa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tiponotificacion')),
            ],
            options={
                'db_table': 'Notificacion',
            },
        ),
    ]
