# Generated by Django 6.0.4 on 2026-04-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('mesas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposito_descontado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por_mesero', models.BooleanField(default=False)),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cajero', to='usuarios.usuario')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogos.estadopago')),
                ('mesero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_mesero', to='usuarios.usuario')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.metodopago')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='mesas.sesionmesa')),
                ('tipo_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipodivision')),
            ],
            options={
                'db_table': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pagos.pago')),
            ],
            options={
                'db_table': 'DetallePago',
            },
        ),
    ]
