# Generated by Django 6.0.4 on 2026-04-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('mesas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valoracion', models.IntegerField(blank=True, null=True)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesas.sesionmesa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.tipocomentario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'Comentario',
            },
        ),
    ]
