# Generated by Django 4.2.30 on 2026-04-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='preci._unit',
            new_name='precio_unit',
        ),
    ]
