# Generated by Django 6.0.4 on 2026-04-20 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('mesas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField()),
                ('num_personas', models.IntegerField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('deposito_por_persona', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposito_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('devolucion_aplicada', models.BooleanField(default=False)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogos.estadoreserva')),
                ('estado_deposito', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalogos.estadodeposito')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='mesas.mesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='usuarios.usuario')),
                ('usuario_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_recibidas', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'Reserva',
            },
        ),
    ]
